### PR TITLE
Create seperate host & user cars for more fine grained control

### PR DESCRIPTION
**Pull request by ghost**
This splits up context a bit. The original context car is still in place. It adds a host and user context so the user can optionally define just a user or host to be displayed how they want, with optional symbols of course.

### CODE REVIEW

**Comment by vadviktor** [comment]
Hey @gregf ,

we should discuss this. So is your idea here to just be able to format the output better, like should only one of the components be displayed OR you also want to be able to _move_ the info around separately?

If you want to be able to move the user and host infos around separately then I see a good point in this PR. If you only wish to turn on/off the text inside, some more env vars are suitable IMHO.

Let me know what was your intention as I don't want to keep redundant cars around.

**Comment by gregf** [comment]
Hmm, Both? I think being able to display just one piece of info and move it around would be good. I looked at other bars before implementing this and this setup seems to be standard in most of them. I was originally going to just add a few env vars to handle this, but after looking to see what that would take this seemed like the better solution to me.

**Review by vadviktor — CHANGES_REQUESTED** [review]
The separation here looks good. I'd only request that according to your intent, which is valid, please remove the context car code and readme section.

**Comment by gregf** [comment]
Sorry I should have been more clear. Context should stay. What if you want user@hostname displayed all in one block. You still need context.

**Comment by vadviktor** [comment]
I for one most certainly don't need 3 cars with overlapping functionalities. If someone misses the context car, then can add it later as a superlightweight plugin because it's just dead simple text :)

**Comment by gregf** [comment]
Fair enough, I'll remove it shortly.

**Comment by vadviktor** [comment]
@gregf here is a reminder 🏓 4 U 👋 no 🏃

**Comment by gregf** [comment]
Think this is ready to roll now if you want to look over it? Sorry, it took me so long, just been busy.

**Review by vadviktor — APPROVED** [review]
There is only a minor typo that I will correct right after merge.

**Pull request merged**
